TLI_FLD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^employment/$', TemplateView.as_view(template_name='employment.html'), name='employment'),
    url(r'^info/$', TemplateView.as_view(template_name='info.html'), name='info'),
    url(r'^student-classes/', include('student_classes.urls', namespace='student-classes')),
    url(r'^class-billing-admin/', include('class_billing_admin.urls', namespace='class-billing-admin')),
    url(r'^scheduling/', include('schedule.urls', namespace='scheduling')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
]

student_classes/urls.py
from django.conf.urls import url

from .views import (scheduled_class_detail_view, scheduled_class_list_view, all_teachers_class_list_view,
                    teacher_class_list_view, teacher_daily_detail_view, attendance_view, past_classes_list_view,
                    all_teachers_daily_detail_view, teacher_past_class_list_view, all_teachers_past_class_list_view)

urlpatterns = [
    url(r'^(?P<id>\d+)/$', scheduled_class_detail_view, name='class-detail'),
    url(r'^student_all/$', scheduled_class_list_view, name='scheduled-classes'),
    url(r'^student_past_all/$', past_classes_list_view, name='past-classes'),
    url(r'^teacher_all/$', teacher_class_list_view, name='teacher-classes'),
    url(r'^teacher_past_classes/$', teacher_past_class_list_view, name='teacher-past-classes'),
    url(r'^teachers_all/$', all_teachers_class_list_view, name='all-teachers-classes'),
    url(r'^teachers_past_classes_all/$', all_teachers_past_class_list_view, name='all-past-teachers-classes'),
    url(r'^(?P<slug>[\w-]+)/teacher_daily/$', teacher_daily_detail_view, name='teacher-daily'),
    url(r'^(?P<slug>[\w-]+)/all_teachers_daily/$', all_teachers_daily_detail_view, name='all-teachers-daily'),
    url(r'^attendance/', attendance_view, name="attendance"),
]

student_classes/forms.py
from django import forms
from .models import StudentClass, TeacherClass, ClassInformation

class TeacherClassForm(forms.ModelForm):
    class Meta:
        model = TeacherClass
        fields = ('student_class', 'teacher_scheduled', 'hours_billed', 'custom_billing')

    def clean_teacher_scheduled(self):
        this_instance = self.instance
        this_id = this_instance.pk
        student_class = StudentClass.objects.get(pk=this_id)
        if self.cleaned_data['teacher_scheduled'] in student_class.unavailable_teachers() and \
                self.cleaned_data['teacher_scheduled'] != student_class.teacherclass.teacher_scheduled:
            raise forms.ValidationError("That teacher is unavailable")
        return self.cleaned_data['teacher_scheduled']

class ClassInformationForm(forms.ModelForm):
    class Meta:
        model = ClassInformation
        fields = '__all__'

    def clean_location(self):
        this_instance = self.instance
        this_id = this_instance.pk
        student_class = StudentClass.objects.get(pk=this_id)
        if self.cleaned_data['location'] in student_class.unavailable_classroom() and \
                self.cleaned_data['location'] != student_class.classinformation.location:
            raise forms.ValidationError("That classroom is unavailable")
        return self.cleaned_data['location']

    def clean_students_in_attendance(self):
        this_instance = self.instance
        this_id = this_instance.pk
        student_class = StudentClass.objects.get(pk=this_id)
        for student in self.cleaned_data['students_in_attendance']:
            if student.profile not in student_class.students_scheduled():
                raise forms.ValidationError("That student is not scheduled for this class")
        return self.cleaned_data['students_in_attendance']

class UpdateTeacherAttendance(forms.ModelForm):
    class Meta:
        model = ClassInformation
        fields = [
            'teacher_attended',
            'class_content',
        ]

class UpdateStudentAttendance(forms.ModelForm):
    class Meta:
        model = ClassInformation
        fields = [
            'student_attended',
        ]

STUDENT_CLASS_STATUS_CHOICES = (
    ('scheduled', 'Scheduled'),
    ('cancellation_request', 'Cancellation_Request'),
    )

class UpdateClassStatus(forms.ModelForm):
    class_status = forms.ChoiceField(choices=STUDENT_CLASS_STATUS_CHOICES)

    class Meta:
        model = ClassInformation
        fields = [
            'class_status',
            'absence_request_reason',
        ]

student_classes/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, JsonResponse
from django.forms.models import model_to_dict

from .models import StudentClass, TeacherClass, ClassInformation
from .forms import UpdateTeacherAttendance, UpdateStudentAttendance, UpdateClassStatus
from accounts.models import Profile
from class_billing_admin.models import StudentBilling
from teacher_billing.models import (TeacherBillingHours, TeacherCustomBillingHours,
                                    TeacherBillingPeriod, TeacherCumulativeCustomBillingHours,
                                    TeacherCumulativeMonthlyPayment, TeacherTotalBillingHours,
                                    TeacherTotalCustomBillingHours)

User = get_user_model()
profile = Profile

def save_billing_information(billing_information, teacher, billing_pk, object):
    print('The obj is this type of class: {}'.format(billing_information['billing_type']))
    if billing_information['billing_type'] == 'custom_for_teacher' or \
            billing_information['billing_type'] == 'customized_nonspecified_teacher':
        billing_obj = TeacherCustomBillingHours.objects.get_or_create(teacher_billed=teacher, \
                                                                            billing=TeacherBillingPeriod.objects.filter(
                                                                            pk=billing_pk).first(), \
                                                                            account=object.student_billing_account)[0]
        if billing_obj.billed_hours == None:
            billing_obj.billed_hours = billing_information['billed_hours']
        else:
            billing_obj.billed_hours = billing_obj.billed_hours + billing_information['billed_hours']
        billing_obj.save()
    elif billing_information['billing_type'] == 'inside':
        billing_obj_tuple = TeacherBillingHours.objects.get_or_create(billing=TeacherBillingPeriod.objects.filter(pk=billing_pk).first(), \
                                                                      teacher_billed=teacher)
        billing_obj = billing_obj_tuple[0]
        if billing_obj.billed_hours == None:
            billing_obj.billed_hours = billing_information['billed_hours']
        else:
            billing_obj.billed_hours = billing_obj.billed_hours + billing_information['billed_hours']
            print('This is the amount of billed hours: {}'.format(billing_obj.billed_hours))
        billing_obj.save()
        print('This is the amount of billed hours: {}'.format(billing_obj.billed_hours))
    else:
        billing_obj_tuple = TeacherBillingHours.objects.get_or_create(billing=TeacherBillingPeriod.objects.filter(pk=billing_pk).first(), \
                                                                      teacher_billed=teacher)
        billing_obj = billing_obj_tuple[0]
        if billing_obj.outside_billed_hours == None:
            billing_obj.outside_billed_hours = billing_information['billed_hours']
        else:
            billing_obj.outside_billed_hours = billing_obj.outside_billed_hours + billing_information['billed_hours']
        billing_obj.save()
        print('This is the amount of billed hours: {}'.format(billing_obj.billed_hours))

def scheduled_class_detail_view(request, id=None):
    current_user = request.user
    obj = StudentClass.objects.get(id=id)
    object = obj.classinformation
    class_is_upcoming = True
    today_date = datetime.datetime.now()
    if obj.scheduled_date <= datetime.datetime.date(today_date):
        class_is_upcoming = False
    original_teacher_attendance = object.teacher_attended
    form = None
    is_teacher_attendance_form = False
    if current_user.profile.teacher == True:
        form = UpdateTeacherAttendance(request.POST or None, instance=object)
        is_teacher_attendance_form = True
    else:
        form = UpdateClassStatus(request.POST or None, instance=object)
    attended = False
    if object.students_in_attendance.filter(id=request.user.id).exists():
        attended = True
    context = {
        "obj": obj,
        "object": object,
        "class_is_upcoming": class_is_upcoming,
        "current_user": current_user,
        "attended": attended,
        "form": form,
    }
    if form.is_valid():
        obj_dict = model_to_dict(obj)
        object_dict = model_to_dict(object)
        object_dict.update(obj_dict)
        if is_teacher_attendance_form == True and object_dict['teacher_attended'] == True and original_teacher_attendance == False:
            billing_information = obj.teacherclass.get_billing_information()
            print('This is the account: {}'.format(billing_information['billing_account']))
            teacher = obj.teacherclass.teacher_scheduled
            billing_pk = billing_information['billing_period'][0]
            print(billing_information['billing_type'])
            save_billing_information(billing_information, teacher, billing_pk, object)
            #save_cumulative_monthly_payment(teacher, billing_pk)
        if is_teacher_attendance_form == True and object_dict['teacher_attended'] == False and original_teacher_attendance == True:
            billing_information = obj.teacherclass.get_billing_information()
            teacher = obj.teacherclass.teacher_scheduled
            print(billing_information['billing_type'])
            amount_of_billed_hours = billing_information['billed_hours']
            print('This many hours are billed {}'.format(amount_of_billed_hours))
            billing_information['billed_hours'] = -billing_information['billed_hours']
            print('This many hours should be subtracted {}'.format(billing_information['billed_hours']))
            billing_pk = billing_information['billing_period'][0]
            save_billing_information(billing_information, teacher, billing_pk, object)
            #save_cumulative_monthly_payment(teacher, billing_pk)
        info_obj = form.save(commit=False)
        info_obj.save()
        messages.success(request, "You have updated class information!")
    template = "student_classes/scheduled-class-detail-view.html"
    return render(request, template, context)

def attendance_view(request):
    #object = get_object_or_404(ClassInformation, id=request.POST.get('object_id'))
    object = get_object_or_404(ClassInformation, pk=request.POST.get('id'))
    attended = False
    if object.students_in_attendance.filter(id=request.user.id).exists():
        object.students_in_attendance.remove(request.user)
        attended = False
        if object.students_who_attended().count() == 0:
            account_id = object.student_billing_account.id
            account_obj = StudentBilling.objects.get(id=account_id)
            account_obj.purchased_class_hours += 1
            account_obj.save()
    else:
        object.students_in_attendance.add(request.user)
        attended = True
        if object.students_who_attended().count() == 1:
            account_id = object.student_billing_account.id
            account_obj = StudentBilling.objects.get(id=account_id)
            account_obj.purchased_class_hours -= 1
            account_obj.save()
    context = {
        "object": object,
        "attended": attended,
    }
    if request.is_ajax():
        html = render_to_string('student_classes/attendance_section.html', context, request=request)
        return JsonResponse({'form': html})

def scheduled_class_list_view(request):
    current_user = request.user
    current_student_profile = Profile.objects.get(user=current_user)
    current_student_schedule = []
    schedule_list = StudentClass.custom_query.upcoming_classes()
    for scheduled_date in schedule_list:
        if current_student_profile in scheduled_date.students_scheduled():
            current_student_schedule.append(scheduled_date)
    context = {
        'heading': "Upcoming Classes",
        'student_schedule_query': current_student_schedule,
        'user_student': current_user,
    }
    template = "student_classes/scheduled-class-list-view.html"
    return render(request, template, context)

def past_classes_list_view(request):
    current_user = request.user
    current_student_profile = Profile.objects.get(user=current_user)
    current_student_schedule = []
    schedule_list = StudentClass.custom_query.past_classes()
    for scheduled_date in schedule_list:
        if current_student_profile in scheduled_date.students_scheduled():
            current_student_schedule.append(scheduled_date)
    context = {
        'heading': "Past Classes",
        'student_schedule_query': current_student_schedule,
        'user_student': current_user,
    }
    template = "student_classes/scheduled-class-list-view.html"
    return render(request, template, context)

def teacher_class_list_view(request):
    current_user = request.user
    current_teacher_profile = Profile.objects.get(user=current_user)
    current_teacher_schedule = []
    list_of_class_dates = []
    schedule_list = StudentClass.custom_query.upcoming_classes()
    for scheduled_class in schedule_list:
        if scheduled_class.teacherclass.teacher_scheduled == current_teacher_profile and scheduled_class.scheduled_date not in list_of_class_dates:
            current_teacher_schedule.append(scheduled_class)
            list_of_class_dates.append(scheduled_class.scheduled_date)
    context = {
        'heading': "Scheduled Classes",
        'teacher_schedule_query': current_teacher_schedule,
        'user_teacher': current_user,
    }
    template = "student_classes/teacher-class-list-view.html"
    return render(request, template, context)

def teacher_past_class_list_view(request):
    current_user = request.user
    current_teacher_profile = Profile.objects.get(user=current_user)
    current_teacher_schedule = []

student_classes/templates/student_classes/all-teachers-class-list-view.html
{% extends "base.html" %}

{% block content %}
<h2><span class="glyphicon glyphicon-calendar"></span>Schedule for All Teachers</h2>

{% for scheduled_class in teacher_schedule_query %}
<li>
    <a href="{% url 'student-classes:all-teachers-daily' scheduled_class.slug %}">{{ scheduled_class.scheduled_date }}</a>
</li>
{% endfor %}

{% endblock %}

student_classes/templates/student_classes/all-teachers-daily-detail-view.html
{% extends "base.html" %}

{% block content %}
<div class="table-responsive">
<h2><span class="glyphicon glyphicon-calendar"></span> Daily Schedule for {{ scheduled_date }}</h2>
    {% for teacher in teacher_query %}
    <h3><a href="/accounts/{{ teacher.id }}">{{ teacher }}</a></h3>
    <table class="table table-dark">
        <thead>
            <tr>
              <th scope="col">Class Time</th>
              <th scope="col">Location</th>
              <th scope="col">Status</th>
              <th scope="col">Student(s) Information</th>
              <th scope="col">Class Information</th>
            </tr>
        </thead>
          <tbody>
          {% for obj in scheduled_class_query %}
            {% if obj.teacherclass.teacher_scheduled == teacher %}
            <tr>
              <td>{{ obj.scheduled_time }}</td>
              <td>{% if obj.classinformation.location != None %}{{ obj.classinformation.location }}{% endif %}</td>
              <td>{{ obj.classinformation.class_status|title }}</td>
              <td>{% for student in obj.student_scheduled.all %}
                  {% if forloop.counter > 1 %}| {% endif %}
                <a href="/accounts/{{ student.id }}">{{ student }}</a>
                {% endfor %}
              </td>
                <td><a href="/student-classes/{{ obj.id }}">Update Class Information</a></td>
            </tr>
            {% endif %}
          {% endfor %}
          </tbody>
    </table>
    {% endfor %}
</div>
{% endblock %}

student_classes/templates/student_classes/attendance_section.html
<form action="{% url 'student-classes:attendance' %}" method="post">
    {% csrf_token %}
    {% if attended %}
    <h4>The following students attended:
    {% for student in object.students_who_attended %}
        {{ student }}<br/>
    {% endfor %}</h4>
        <button type="submit" id="attendance" name="object_id" value="{{ object.pk }}" class="btn btn-primary">Disconfirm Attendance</button>
    {% else %}
    <h4>The following students attended:
    {% for student in object.students_who_attended %}
        {{ student }}<br/>
        {% endfor %}</h4>
        <button type="submit" id="attendance" name="object_id" value="{{ object.pk }}" class="btn btn-primary">Confirm Attendance</button>
    {% endif %}
</form>

student_classes/templates/student_classes/scheduled-class-detail-view.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap3 %}
{% include 'alerts.html' %}
<div class="table-responsive">
    <h1 class="class_info">Class Information</h1>
    <h2 class="class_info">Scheduling</h2>
    <h3>Class is upcoming: {{ class_is_upcoming }}</h3>
    <table class="table table-dark">
        <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Time</th>
              <th scope="col">Teacher</th>
              <th scope="col">Location</th>
              <th scope="col">Students</th>
            </tr>
        </thead>
          <tbody>
            <tr>
              <td>{{ obj.scheduled_date }}</td>
              <td>{{ obj.scheduled_time }}</td>
              <td><a href="/accounts/{{ obj.teacherclass.teacher_scheduled.id }}">{{ obj.teacherclass.teacher_scheduled }}</a></td>
              <td>{{ object.location }}</td>
              <td>{% for student in obj.student_scheduled.all %}
                  {% if forloop.counter > 1 %}| {% endif %}
                <a href="/accounts/{{ student.id }}">{{ student }}</a>
                {% endfor %}
              </td>
            </tr>
          </tbody>
    </table>
    <h2 class="class_info">Class Records</h2>
    <table class="table table-dark">
        <thead>
            <tr>
              <th scope="col">Class Status</th>
              <th scope="col">Class Contents</th>
                <th scope="col">
                  {% if object.class_status == 'cancellation_request' %}Student Absence Request Reason
                  {% else %}Other Information{% endif %}</th>
              {% if current_user.profile.teacher %}<th scope="col">Attendance</th>{% endif %}
            </tr>
        </thead>
          <tbody>
            <tr>
              <td>{{ object.class_status|title }}</td>
              <td>{{ object.class_content }}</td>
              <td>{{ object.absence_request_reason  }}</td>
              {% if current_user.profile.teacher %}<td>{{ object.teacher_attended }}</td>{% endif %}
            </tr>
          </tbody>
    </table>
</div>

{% if current_user.profile.teacher %}
    <button id="teacher-under" class="btn btn-default">Update Class Information</button><br/>
    <div id="teacher-attendance-content">

        <form method="post" class="update-form" action=".">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Submit Class Information" class="btn btn-primary" id="teacher-class-info-btn">
        </form>
    <br/>
    <br/>
    </div>
{% else %}
<h3 class="class_info">Attendance</h3>
<div style="text-align:center;">
    <button id="class-status-under" class="btn btn-default">Request Absence/Scheduling Update</button><br/>
</div>
<div id="class-status-content">
    <form method="post" class="class-status-form" action=".">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Update Class Information" class="btn btn-primary" id="class-status-btn">
    </form>

</div>
    {% if class_is_upcoming == False %}
    <div id="attendance-section">
        {% include 'student_classes/attendance_section.html' %}
    </div>
    {% endif %}

{% endif %}

</div>

{% endblock %}

student_classes/templates/student_classes/scheduled-class-list-view.html
{% extends "base.html" %}

{% block content %}
<h2><span class="glyphicon glyphicon-calendar"></span>{{ heading }} for {{ user_student }}</h2>

    <table class="table table-dark">
        <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Time</th>
              <th scope="col">Teacher</th>
              <th scope="col">Students</th>
              <th scope="col">Class Location</th>
            </tr>
        </thead>
          <tbody>
          {% for date in student_schedule_query %}
            <tr>
                <td><a href="/student-classes/{{ date.id }}">{{ date.scheduled_date }}</a></td>
              <td>{{ date.scheduled_time }}</td>
              <td>{{ date.teacherclass.teacher_scheduled }}</td>
              <td>{% for student in date.student_scheduled.all %}
                    {% if forloop.counter > 1 %}| {% endif %}
                    {{ student }}
                  {% endfor %}
              </td>
              <td>{% if date.classinformation.location != None %}{{ date.classinformation.location|title }}{% endif %}</td>
            </tr>
          {% endfor %}
          </tbody>
    </table>

{% endblock %}

student_classes/templates/student_classes/student-attendance.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap3 %}
{% include 'alerts.html' %}
<h2>Confirmation of Student Attendance</h2>
<form method="POST" action=".">{% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update">
</form>
{% endblock %}

student_classes/templates/student_classes/teacher-attendance.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap3 %}
{% include 'alerts.html' %}
<h2>Confirmation of Teacher Attendance</h2>
<form method="POST" action=".">{% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Update">
</form>
{% endblock %}

student_classes/templates/student_classes/teacher-class-list-view.html
{% extends "base.html" %}

{% block content %}
<h2><span class="glyphicon glyphicon-calendar"></span>{{ heading }} for {{ user_teacher }}</h2>

{% for scheduled_class in teacher_schedule_query %}
<li>
    <a href="{% url 'student-classes:teacher-daily' scheduled_class.slug %}">{{ scheduled_class.scheduled_date }}</a>
</li>
{% endfor %}

{% endblock %}

student_classes/templates/student_classes/teacher-daily-detail-view.html
{% extends "base.html" %}

{% block content %}
<div class="table-responsive">
<h2><span class="glyphicon glyphicon-calendar"></span> Daily Schedule for {{ user.profile.given_name }} {{ user.profile.surname }} on {{ scheduled_date }}</h2>
    <table class="table table-dark">
        <thead>
            <tr>
              <th scope="col">Class Time</th>
              <th scope="col">Location</th>
              <th scope="col">Status</th>
              <th scope="col">Student(s) Information</th>
              <th scope="col">Class Information</th>
            </tr>
        </thead>
          <tbody>
          {% for obj in user_query %}
            <tr>
              <td>{{ obj.scheduled_time }}</td>
              <td>{% if obj.classinformation.location != None %}{{ obj.classinformation.location }}{% endif %}</td>
              <td>{{ obj.classinformation.class_status|title }}</td>
              <td>{% for student in obj.student_scheduled.all %}
                  {% if forloop.counter > 1 %}| {% endif %}
                <a href="/accounts/{{ student.id }}">{{ student }}</a>
                {% endfor %}
              </td>
                <td><a href="/student-classes/{{ obj.id }}">Update Class Information</a></td>
            </tr>
          {% endfor %}
          </tbody>
    </table>
</div>
{% endblock %}

student_classes/templates/student_classes/update-class-status.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap3 %}
{% include 'alerts.html' %}
<h2>Update Class Status</h2>
<h3>If you would like to reschedule or cancel the class,<br>
Please state your name and reason for rescheduling <br>
in the box below. Thank you!</h3>
<form method="POST" action=".">{% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" id="update-class-status" value="Update">
</form>
{% endblock %}