TLI_FLD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^employment/$', TemplateView.as_view(template_name='employment.html'), name='employment'),
    url(r'^info/$', TemplateView.as_view(template_name='info.html'), name='info'),
    url(r'^student-classes/', include('student_classes.urls', namespace='student-classes')),
    url(r'^class-billing-admin/', include('class_billing_admin.urls', namespace='class-billing-admin')),
    url(r'^scheduling/', include('schedule.urls', namespace='scheduling')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
]

accounts/urls.py
from django.conf.urls import url

from .views import register, user_login, user_logout, profile_model_detail_view, student_profile_detail_view

urlpatterns = [
    url(r'^profile/$', profile_model_detail_view, name='profile-detail'), #user regular expression for username
    url(r'^(?P<id>\d+)/$', student_profile_detail_view, name='student-detail'),
    url(r'^register/$', register, name='register'),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
]

class_billing_admin/urls.py
from django.conf.urls import url

from .views import low_hours_list_view, class_billing_detail_view, billing_accounts_list_view

urlpatterns = [
    url(r'^$', billing_accounts_list_view, name='billing-accounts-list'),
    url(r'^low_hours_list/$', low_hours_list_view, name='low-hours'),
    url(r'^(?P<slug>[\w-]+)/billing_detail/$', class_billing_detail_view, name='class-billing-detail'),
]

contacts/urls.py
from django.conf.urls import url

from .views import message_list_view, message_detail_view, message_sent_view, message_list_student_schedule_view, \
                    message_list_teacher_view, message_list_student_view, message_list_teacher_schedule_view, \
                    message_list_student_low_hours_view, message_list_student_unconfirmed_view, \
                    message_list_teacher_unconfirmed_view

urlpatterns = [
    url(r'^message_list_teacher_unconfirmed/$', message_list_teacher_unconfirmed_view, name="message_list_teacher_unconfirmed"),
    url(r'^message_list_student_unconfirmed/$', message_list_student_unconfirmed_view, name="message_list_student_unconfirmed"),
    url(r'^message_list_teacher/$', message_list_teacher_view, name="message_list_teacher"),
    url(r'^message_list_student/$', message_list_student_view, name="message_list_student"),
    url(r'^message_list_student_low_hours/$', message_list_student_low_hours_view, name="message_list_student_low_hours"),
    url(r'^message_list_teacher_schedule/$', message_list_teacher_schedule_view, name="message_list_teacher_schedule"),
    url(r'^message_list_student_schedule/$', message_list_student_schedule_view, name="message_list_student_schedule"),
    url(r'^message_list/$', message_list_view, name="message_list"),
    url(r'^(?P<id>\d+)/message_sent/$', message_sent_view, name="message_sent"),
    url(r'^(?P<id>\d+)/$', message_detail_view, name="message_detail"),
]

student_classes/urls.py
from django.conf.urls import url

from .views import (scheduled_class_detail_view, scheduled_class_list_view, all_teachers_class_list_view,
                    teacher_class_list_view, teacher_daily_detail_view, attendance_view, past_classes_list_view,
                    all_teachers_daily_detail_view, teacher_past_class_list_view, all_teachers_past_class_list_view)

urlpatterns = [
    url(r'^(?P<id>\d+)/$', scheduled_class_detail_view, name='class-detail'),
    url(r'^student_all/$', scheduled_class_list_view, name='scheduled-classes'),
    url(r'^student_past_all/$', past_classes_list_view, name='past-classes'),
    url(r'^teacher_all/$', teacher_class_list_view, name='teacher-classes'),
    url(r'^teacher_past_classes/$', teacher_past_class_list_view, name='teacher-past-classes'),
    url(r'^teachers_all/$', all_teachers_class_list_view, name='all-teachers-classes'),
    url(r'^teachers_past_classes_all/$', all_teachers_past_class_list_view, name='all-past-teachers-classes'),
    url(r'^(?P<slug>[\w-]+)/teacher_daily/$', teacher_daily_detail_view, name='teacher-daily'),
    url(r'^(?P<slug>[\w-]+)/all_teachers_daily/$', all_teachers_daily_detail_view, name='all-teachers-daily'),
    url(r'^attendance/', attendance_view, name="attendance"),
]

contacts/models.py
from django.db import models

MESSAGE_TYPE = (
    ("teacher_unconfirmed", "Teacher Attendance Unconfirmed"),
    ("student_unconfirmed", "Student Attendance Unconfirmed"),
    ("teacher_schedules", "Teacher's Schedules"),
    ("student_schedules", "Student's Schedules"),
    ("all_teachers", "All Teachers"),
    ("all_students", "All Students"),
    ("students_low_hours", "Students Low on Hours"),
    ("all_users", "All Users"),
    )

class ContactMessages(models.Model):
    title = models.CharField(max_length=120)
    message_text = models.TextField()
    message_type = models.CharField(max_length=300, choices=MESSAGE_TYPE, default='teacher_schedules')
    timestamp = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(blank=True, null=True)
    pwd = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Contact Messages'

contacts/forms.py
from django import forms

from .models import ContactMessages

class ContactMessagesForm(forms.ModelForm):
    class Meta:
        model = ContactMessages
        fields = ('message_text','email', 'pwd')
        widgets = {'pwd': forms.PasswordInput()}

contacts/views.py
import datetime
import smtplib

from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string

from .models import ContactMessages
from .forms import ContactMessagesForm
from accounts.models import Profile
from class_billing_admin.models import StudentBilling
from student_classes.models import TeacherClass, StudentClass


def message_list_teacher_unconfirmed_view(request):
    query_set = ContactMessages.objects.filter(message_type="teacher_unconfirmed")
    title = 'Messages for Teachers with Unconfirmed Attendance'
    context = {
        'title': title,
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_list_student_unconfirmed_view(request):
    query_set = ContactMessages.objects.filter(message_type="student_unconfirmed")
    title = 'Messages for Students with Unconfirmed Attendance'
    context = {
        'title': title,
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_list_teacher_view(request):
    query_set = ContactMessages.objects.filter(message_type="all_teachers")
    title = 'Messages for Teachers'
    context = {
        'title': title,
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_list_student_view(request):
    query_set = ContactMessages.objects.filter(message_type="all_students")
    title = 'Messages for Students'
    context = {
        'title': title,
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_list_teacher_schedule_view(request):
    query_set = ContactMessages.objects.filter(message_type="teacher_schedules")
    title = 'Scheduling Messages for Teachers'
    context = {
        'title': title,
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_list_student_schedule_view(request):
    query_set = ContactMessages.objects.filter(message_type="student_schedules")
    title = 'Scheduling Messages for Students'
    context = {
        'title': title,
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_list_student_low_hours_view(request):
    query_set = ContactMessages.objects.filter(message_type="students_low_hours")
    title = 'Messages for Students with Low Hours'
    context = {
        'title': title,
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_list_view(request):
    query_set = ContactMessages.objects.filter(message_type="all_users")
    context = {
        'query_set': query_set,
    }
    template = 'contacts/message_list.html'
    return render(request, template, context)

def message_detail_view(request, id=None):
    object = get_object_or_404(ContactMessages, id=id)
    low_student_hours_dict = {}
    if object.message_type == "student_schedules":
        query = StudentClass.custom_query.student_email_query()
    elif object.message_type == "teacher_schedules":
        query = TeacherClass.custom_query.teacher_email_query()
    elif object.message_type == "all_students":
        query = Profile.custom_query.student_email_query()
    elif object.message_type == "all_teachers":
        query = Profile.custom_query.teacher_email_query()
    elif object.message_type == "teacher_unconfirmed":
        qs = StudentClass.custom_query.past_classes_student_confirmed_teacher_unconfirmed()
        query = [scheduled_class.teacherclass.teacher_scheduled for scheduled_class in qs]
    elif object.message_type == "student_unconfirmed":
        qs = StudentClass.custom_query.past_classes_teacher_confirmed_student_unconfirmed()
        profile_query = [scheduled_class.classinformation.students_not_attended() for scheduled_class in qs]
        query = []
        for sub_query in profile_query:
            for q in sub_query:
                if q not in query:
                    query.append(q)
    elif object.message_type == "students_low_hours":
        query = ''
        low_student_hours_dict = StudentBilling.custom_query.student_email_under_two_hours()
    else:
        query = Profile.custom_query.all_users_email_query()
    if request.method == 'POST':
        form = ContactMessagesForm(request.POST or None, instance=object)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
    else:
        form = ContactMessagesForm()
    context = {
        'object': object,
        'low_student_hours_dict': low_student_hours_dict,
        'query': query,
        'form': form,
    }
    if request.is_ajax():
        obj_dict = model_to_dict(object)
        html = render_to_string('contacts/message_form_update.html', context, request=request)
        obj_dict.update({'form': html})
        return JsonResponse(obj_dict)
    template = 'contacts/message_view.html'
    return render(request, template, context)

def teacher_scheduling_email(object, tomorrow, smtpObj, send_from):
    class_query = StudentClass.objects.filter(scheduled_date=tomorrow)
    teacher_email_query = TeacherClass.custom_query.teacher_email_query()
    for teacher in teacher_email_query:
        class_time_list = []
        student_list = []
        for obj in class_query:
            if obj.teacherclass.teacher_scheduled == teacher:
                class_time_list.append(str(obj.scheduled_time)[:5])
                student_list.append(obj.student_scheduled.first().user.username)
        schedule_str = ''
        for c in range(0, len(class_time_list)):
            daily_str = "\r\n%s -- %s" % (class_time_list[c], student_list[c])
            schedule_string = schedule_str
            schedule_str = schedule_string + ' ' + daily_str
        teacher_name = teacher.given_name
        send_to = teacher.contact_email
        message_title = object.title
        message_text = object.message_text
        message_string = '''Subject: %s\n
                            \r\n\r\nHello %s, \r\n\r\nThis is your schedule for tomorrow %s/%s/%s: 
                                %s \r\n\r\n%s \r\n\r\nHave a great day!
                             ''' % (message_title, teacher_name, tomorrow.month, tomorrow.day, tomorrow.year,
                                    schedule_str, message_text)
        smtpObj.sendmail(send_from, send_to, message_string)

def student_scheduling_email(object, tomorrow, smtpObj, send_from):
    class_query = StudentClass.objects.filter(scheduled_date=tomorrow)
    student_email_query = StudentClass.custom_query.student_email_query()
    for student in student_email_query:
        class_time_list = []
        teacher_list = []
        for obj in class_query:
            if student in obj.student_scheduled.all():
                class_time_list.append(str(obj.scheduled_time)[:5])
                teacher_list.append(obj.teacherclass.teacher_scheduled)
                print(obj.teacherclass.teacher_scheduled)
        schedule_str = ''
        for c in range(0, len(class_time_list)):
            daily_str = "\r\n%s -- %s" % (class_time_list[c], teacher_list[c])
            schedule_string = schedule_str
            schedule_str = schedule_string + ' ' + daily_str
        student_name = student.given_name
        send_to = student.contact_email
        message_title = object.title
        message_text = object.message_text
        message_string = '''Subject: %s\n
                            \r\n\r\nHello %s, \r\n\r\nThis is your schedule for tomorrow %s/%s/%s: 
                            %s \r\n\r\n%s \r\n\r\nHave a great day!
                             ''' % (message_title, student_name, tomorrow.month, tomorrow.day, tomorrow.year,
                                    schedule_str, message_text)
        smtpObj.sendmail(send_from, send_to, message_string)

def student_email(object, smtpObj, send_from):
    student_email_query = Profile.custom_query.student_email_query()
    for student in student_email_query:
        student_name = student.given_name
        send_to = student.contact_email
        message_title = object.title
        message_text = object.message_text
        message_string = '''Subject: %s\n
                            \r\n\r\nHello %s, 
                            \r\n\r\n%s \r\n\r\nHave a great day!
                            ''' % (message_title, student_name, message_text)
        smtpObj.sendmail(send_from, send_to, message_string)

def student_low_hours_email(object, smtpObj, send_from):
    account_query = StudentBilling.custom_query.under_two_hours()
    email_list = []
    for account in account_query:
        account_email_list = [account.contact_email for account in account.student_account.all()]
        for email in account_email_list:
            email_list.append(email)
    for email in email_list:
        student_name = 'Valued Customer'
        send_to = email
        message_title = object.title
        message_text = object.message_text
        message_string = '''Subject: %s\n
                            \r\n\r\nDear %s,
                            \r\n%s \r\n\r\nHave a great day!
                            ''' % (message_title, student_name, message_text)
        smtpObj.sendmail(send_from, send_to, message_string)

def teacher_email(object, smtpObj, send_from):
    teacher_email_query = Profile.custom_query.teacher_email_query()
    for teacher in teacher_email_query:
        teacher_name = teacher.given_name
        send_to = teacher.contact_email
        message_title = object.title
        message_text = object.message_text
        message_string = '''Subject: %s\n

templates/alerts.html
<div class="messages">
    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-{{ message.tags }}">
                {{ message }}
            </p>
        {% endfor %}
    {% endif %}
</div>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Taipei Language Institute Department of Foreign Languages</title>

        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery=1 %}
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css" integrity="sha384-jzngWsPS6op3fgRCDTESqrEJwRKck+CILhJVO5VvaAZCq8JYf8HsR/HPpBOOPZfR" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Francois+One|Hind+Siliguri|Teko" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'TLI_FLD/css/master.css' %}">
    </head>
    <body style="background-color:black">
        {% include 'navbar.html' %}

        <div class="content container mycontent">
            <div class="jumbotron">
                {% block content %}

                {% endblock %}
            </div>
        </div>>
        {% include 'footer.html' %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script type="text/javascript" scr="{% static 'TLI_FLD/js/master.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function(event) {
            //  $('#update-class-status').click(function(){
            //    return confirm("Are you sure that you would like to update the class status?");
            //  });

            //  $('#update-profile').click(function() {
            //    return alert("This profile has been updated");
            //  });

              $(function() {
                setTimeout(function() {
                  $('.alert').slideUp(2000);
                }, 5000);
              });
              $(document).on('click', '#attendance', function(event) {
                event.preventDefault();
                var pk = $(this).attr('value');
                $.ajax({
                  type: 'POST',
                  url: '{% url "student-classes:attendance" %}',
                  data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                  dataType: 'json',
                  success: function(response) {
                    $('#attendance-section').html(response['form']);
                  },
                  error: function(rs, e) {
                    console.log(rs.responseText);
                  },
                });
              });

              $('#teacher-attendance-content').hide();
              $('#teacher-under').click(function() {
                  $("#teacher-attendance-content").show(1000);
                  $('#teacher-under').hide();
                });

                $('#teacher-hide').click(function() {
                    $("#teacher-attendance-content").hide(1000);
                    $('#teacher-under').show();
                  });

              $('#class-status-content').hide();
              $('#class-status-under').click(function() {
                  $("#class-status-content").show(1000);
                  $('#class-status-under').hide();
                });

              $('#edit-profile-content').hide();
              $('#edit-profile-under').click(function() {
                  $("#edit-profile-content").show(1000);
                  $('#edit-profile-under').hide();
                });

              $(document).on('submit', '.update-profile-form', function(event) {
                event.preventDefault();
                $.ajax({
                  type: 'POST',
                  url: $(this).attr('action'),
                  data: $(this).serialize(),
                  dataType: 'json',
                  success: function(response) {
                    $('#edit-profile-form').html(response['form']);
                    $('#profile_details').html(`<h3>Username: ${response['username']}</h3>
                                                <h3>Name: ${response['given_name']} ${response['surname']}</h3>
                                                <h4>Email: ${response['contact_email']}</h4>
                                                <h4>Status: ${response['status']}</h4>
                                                <h4>${response['course_content_preferences']}</h4>
                                                <h4>${response['other_personal_information']}</h4><br/>`);
                    $('#edit-profile-under').show();
                    $('#edit-profile-content').hide();

                  },
                  error: function(rs, e) {
                    console.log(e);
                    console.log(rs.restponseText);
                  },
                });
              });

              $(document).on('submit', '.update-message-form', function(event) {
                  event.preventDefault();
                  $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function(response) {
                      $('#show_message_form').html(response['form']);
                      $('#message_details').html(`${response['title']}<br/>
                                                  <p>${response['message_text']}</p><br/>
                                                `)
                      $('#message_details').show();
                      $('.showunder').show();
                      $('#show_message_form').hide();
                    },
                    error: function(rs, e) {
                      console.log(e);
                      console.log(rs.responseText);
                    },
                  });
              });

              $('.under').hide();

              $('.showunder').click(function() {
                $(".under").show(1000);
                $('.showunder').hide();
              });

              $('.hideunder').click(function() {
                $(".under").hide(1000);
                $('.showunder').show();
              });
            });
        </script>
    </body>

</html>

templates/contact.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Contact Information</h1>
        <p>TLI Roosevel Language Center is conveniently located near Taipower Building MRT Station</p>
        <p>TEL: (886-2)2367-8228</p>
        <p>FAX: (886-2)2363-4857 4F</p>
        <p>ADDRESS: No. 50 Roosevelt Rd., Sec.3, Taipei</p>

</div>
{% endblock %}

templates/employment.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Employment Information</h1>
        <h2>Taipei Language Institute is currently hiring teachers for the following positions:</h2>
        <p>English Teacher: Full/Part Time </br>
            Japanese Teacher: Full/Part Time</br>
            German Teacher: Part Time </br>
            Korean Teacher: Part Time</p>
        <p>For enquiries about employment opportunities, feel free to contact us. We look forward to hearing from you!</p>

</div>
{% endblock %}

templates/footer.html
{% load staticfiles %}
<footer id="myFooter">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h5>Get started</h5>
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:register' %}">Sign up</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h5>About us</h5>
                <ul>
                    <li><a href="{% url 'info' %}">Company Information</a></li>
                    <li><a href="{% url 'contact' %}">Contact us</a></li>
                    <li><a href="{% url 'employment' %}">Employment</a></li>
                </ul>
            </div>
            <div class="col-sm-3 info">
                <h5>Information</h5>
                <p>Taipei Language Institute offers foreign language instruction in English, Japanese, and a variety of other
                    languages to students of all ages.</p>
            </div>
            <div class="col-sm-3">
                <img src="{% static 'TLI_FLD/images/TLI_logo_color_resize.png' %}" alt="Taipei Language Institute" class="loco_logo"/>
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-fixed-top mynav" role="navigation">
    <div class="container main_part">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsemenu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand mynav" href="{% url 'home' %}">TLI Foreign Language Department</a>
        </div>
        <div class="collapse navbar-collapse" id="collapsemenu">
            <ul class="nav navbar-nav navbar-right list_items">
             {% if user.is_authenticated and user.is_superuser %}
                {% include 'navbar_admin.html' %}
             {% elif user.is_authenticated and user.is_superuser == False %}
                {% if user.profile.teacher %}
                <li class="nav-item"><a href="{% url 'accounts:profile-detail' %}">User Profile</a></li>
                <li class="nav-item"><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                <li class="nav-item"><a href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item dropdown mydropnav">
                    <a class="nav-link dropdown-toggle mydropnav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Schedule
                    </a>
                    <div class="dropdown-menu mynav"  aria-labelledby="navbarDropdown">
                        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'student-classes:teacher-classes' %}">Upcoming Classes</a></div>
                        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'student-classes:teacher-past-classes' %}">Past Classes</a></div>
                    </div>
                </li>
                {% else %}
                <li class="nav-item"><a href="{% url 'accounts:profile-detail' %}">User Profile</a></li>
                <li class="nav-item"><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                <li class="nav-item dropdown mydropnav">
                    <a class="nav-link dropdown-toggle mydropnav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Schedule
                    </a>
                    <div class="dropdown-menu mynav"  aria-labelledby="navbarDropdown">
                        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'student-classes:scheduled-classes' %}">Upcoming Classes</a></div>
                        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'student-classes:past-classes' %}">Past Classes</a></div>
                    </div>
                </li>
                <li class="nav-item"><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
             {% else %}
                <li class="nav-item"><a href="{% url 'info' %}">About</a></li>
                <li class="nav-item"><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li class="nav-item"><a href="{% url 'accounts:register' %}">Sign Up</a></li>
                <li class="nav-item"><a href="{% url 'contact' %}">Contact</a></li>
                <li class="nav-item"><a href="{% url 'admin:index' %}">Admin</a></li>
             {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/navbar_admin.html
<li class="nav-item dropdown mydropnav">
    <a class="nav-link dropdown-toggle mydropnav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Schedule
    </a>
    <div class="dropdown-menu mynav"  aria-labelledby="navbarDropdown">
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'student-classes:all-teachers-classes' %}">Upcoming Classes</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'student-classes:all-past-teachers-classes' %}">Past Classes</a></div>
    </div>
</li>
<li class="nav-item"><a href="{% url 'accounts:logout' %}">Log Out</a></li>
<li class="nav-item"><a href="{% url 'admin:index' %}">Admin</a></li>
<li class="nav-item dropdown mydropnav">
    <a class="nav-link dropdown-toggle mydropnav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Billing
    </a>
    <div class="dropdown-menu mynav"  aria-labelledby="navbarDropdown">
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'class-billing-admin:billing-accounts-list' %}">All Accounts</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'class-billing-admin:low-hours' %}">Low Hours</a></div>
    </div>
</li>
<li class="nav-item dropdown mydropnav">
    <a class="nav-link dropdown-toggle mydropnav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Message
    </a>
    <div class="dropdown-menu mynav"  aria-labelledby="navbarDropdown">
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list_teacher_schedule' %}">Teacher's Schedules</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list_student_schedule' %}">Student's Schedules</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list_student_low_hours' %}">Purchase Reminder</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list_student' %}">All Students</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list_teacher' %}">All Teachers</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list_student_unconfirmed' %}">Unconfirmed Attendance Students</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list_teacher_unconfirmed' %}">Unconfirmed Attendance Teachers</a></div>
        <div class="dropdown-divider"><a class="dropdown-item" href="{% url 'contacts:message_list' %}">All Users</a></div>
    </div>
</li>